### ISSUE TITLE
Implement player basic (fist) attack

### ISSUE THREAD

**Issue by samperumal** [samperumal/samperumal.github.io#17]

**Comment by stankiewiczm** [comment]
Would this be a case of "walk into a spot occupied by the monster"?

**Comment by samperumal** [comment]
That's ideally what I was thinking, yeah.

**Comment by stankiewiczm** [comment]
My thoughts for this were (are)
 - Walking into a monster area will attack with fists/melee weapon
 - fists cause 1 damage
 - melee weapons do x damage, as specified by weapon
 - damage taken to be min(attacker.damage - defender.armour, 1)
Does that sound like a decent starting setup?

**Comment by antonburger** [comment]
Sounds reasonable to me.

**Comment by stankiewiczm** [comment]
Monster hitting mechanics in https://github.com/samperumal/samperumal.github.io/pull/42

**Comment by stankiewiczm** [comment]
Closing issue (walking into monsters hits them with current weapon (fists = 1))
